### ISSUE TITLE
env_projectedtexture bugs

### ISSUE THREAD

**Issue by marnamai** [Jesse-Culver/source-sdk-2013-community-edition#3]
map used during testing https://www.dropbox.com/s/kpk9epyx5sfh2i8/projectedtexture_maps.7z?dl=0

![wrong_projection](https://cloud.githubusercontent.com/assets/4421492/18297626/464c156c-74b2-11e6-833e-2e72baf71ed4.jpg)
![texture repeat](https://cloud.githubusercontent.com/assets/4421492/18297627/4663976e-74b2-11e6-8a61-5e33f30a5f89.jpg)
![grain shadow_disconnect](https://cloud.githubusercontent.com/assets/4421492/18297628/46722d56-74b2-11e6-8d8c-3395e7c40da7.jpg)
![jitter_target](https://cloud.githubusercontent.com/assets/4421492/18297629/46763540-74b2-11e6-8e22-50b262771b73.jpg)

**Comment by AlpyneDreams** [comment]
I've fixed the bias errors and targeting has been fixed for ages.
