### ISSUE TITLE
VGUI scrollbars regression

### ISSUE THREAD

**Issue by Juesto** [Jesse-Culver/source-sdk-2013-community-edition#8]
If you remember, this started in 2013. they were never "pressed" like this.
i remember it confused me at first.
i doubt if it's fixable mod-wise
![image](https://cloud.githubusercontent.com/assets/12691160/18371146/7d9ce90e-7608-11e6-9a6f-950e3066c2a8.png)

**Comment by kebokyo** [comment]
This may have been made for a reason, sooo... Yeah, I don't think this is fixable. Maybe when we're bored we can try to fix it but it isn't really a priority.
